export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR'

export const SET_STUDENT_LIST = 'SET_STUDENT_LIST'
export const SET_STUDENT_LIST_SUCCESS = 'SET_STUDENT_LIST_SUCCESS'
export const SET_STUDENT_LIST_ERROR = 'SET_STUDENT_LIST_ERROR'

export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA'
export const UPDATE_STUDENT_DATA_SUCCESS = 'UPDATE_STUDENT_DATA_SUCCESS'
export const UPDATE_STUDENT_DATA_ERROR = 'UPDATE_STUDENT_DATA_ERROR'

export const FETCH_STUDENT_NATIONALITY = 'FETCH_STUDENT_NATIONALITY'
export const FETCH_STUDENT_NATIONALITY_SUCCESS = 'FETCH_STUDENT_NATIONALITY_SUCCESS'
export const FETCH_STUDENT_NATIONALITY_ERROR = 'FETCH_STUDENT_NATIONALITY_ERROR'

export const UPDATE_STUDENT_NATIONALITY = 'UPDATE_STUDENT_NATIONALITY'
export const UPDATE_STUDENT_NATIONALITY_SUCCESS = 'UPDATE_STUDENT_NATIONALITY_SUCCESS'
export const UPDATE_STUDENT_NATIONALITY_ERROR = 'UPDATE_STUDENT_NATIONALITY_ERROR'

export const FETCH_STUDENT_FAMILY_MEMBERS = 'FETCH_STUDENT_FAMILY_MEMBERS'
export const FETCH_STUDENT_FAMILY_MEMBERS_SUCCESS = 'FETCH_STUDENT_FAMILY_MEMBERS_SUCCESS'
export const FETCH_STUDENT_FAMILY_MEMBERS_ERROR = 'FETCH_STUDENT_FAMILY_MEMBERS_ERROR'

export const UPDATE_STUDENT_FAMILY_MEMBERS = 'UPDATE_STUDENT_FAMILY_MEMBERS'
export const UPDATE_STUDENT_FAMILY_MEMBERS_SUCCESS = 'UPDATE_STUDENT_FAMILY_MEMBERS_SUCCESS'
export const UPDATE_STUDENT_FAMILY_MEMBERS_ERROR = 'UPDATE_STUDENT_FAMILY_MEMBERS_ERROR'

export const SET_FAMILY_MEMBERS = 'SET_FAMILY_MEMBERS'
export const SET_FAMILY_MEMBERS_SUCCESS = 'SET_FAMILY_MEMBERS_SUCCESS'
export const SET_FAMILY_MEMBERS_ERROR = 'SET_FAMILY_MEMBERS_ERROR'

export const DELETE_FAMILY_MEMBERS = 'DELETE_FAMILY_MEMBERS'
export const DELETE_FAMILY_MEMBERS_SUCCESS = 'DELETE_FAMILY_MEMBERS_SUCCESS'
export const DELETE_FAMILY_MEMBERS_ERROR = 'DELETE_FAMILY_MEMBERS_SUCCESS'

export const FETCH_FAMILY_MEMBER_NATIONALITY = 'FETCH_FAMILY_MEMBER_NATIONALITY'
export const FETCH_FAMILY_MEMBER_NATIONALITY_SUCCESS = 'FETCH_FAMILY_MEMBER_NATIONALITY_SUCCESS'
export const FETCH_FAMILY_MEMBER_NATIONALITY_ERROR = 'FETCH_FAMILY_MEMBER_NATIONALITY_ERROR'

export const UPDATE_FAMILY_MEMBER_NATIONALITY = 'UPDATE_FAMILY_MEMBER_NATIONALITY'
export const UPDATE_FAMILY_MEMBER_NATIONALITY_SUCCESS = 'UPDATE_FAMILY_MEMBER_NATIONALITY_SUCCESS'
export const UPDATE_FAMILY_MEMBER_NATIONALITY_ERROR = 'UPDATE_FAMILY_MEMBER_NATIONALITY_ERROR'

export const FETCH_ALL_NATIONALITIES = 'FETCH_ALL_NATIONALITIES'
export const FETCH_ALL_NATIONALITIES_SUCCESS = 'FETCH_ALL_NATIONALITIES_SUCCESS'
export const FETCH_ALL_NATIONALITIES_ERROR = 'FETCH_ALL_NATIONALITIES_ERROR'

export const FETCH_ACTIVE_SECTIONS = 'FETCH_ACTIVE_SECTIONS'
export const ADD_ROW_FAMILY = 'ADD_ROW_FAMILY'

export const SUBMIT_STUDENT_SECTION = 'SUBMIT_STUDENT_SECTION'
export const SELECTED_STUDENT_ROW = 'SELECTED_STUDENT_ROW'

export const SELECTED_ROLE = 'SELECTED_ROLE'
export const NATIONALITY_INDICATOR = 'NATIONALITY_INDICATOR'
export const SUBMIT_BUTTON_VALUE = 'SUBMIT_BUTTON_VALUE'
export const ADD_BUTTON_VALUE = 'ADD_BUTTON_VALUE'

export const SELECTED_FAMILY_ROW = 'SELECTED_FAMILY_ROW'
export const FAMILY_NATIONALITY_INDICATOR = 'FAMILY_NATIONALITY_INDICATOR'

export const ADD_FAMILY_BUTTON = 'ADD_FAMILY_BUTTON'
export const IS_ADD_BUTTON_CLICKED = 'IS_ADD_BUTTON_CLICKED'

export const DELETE_SET_UP = 'DELETE_SET_UP'
export const DELETE_SET_UP_SUCCESS = 'DELETE_SET_UP_SUCCESS'
export const DELETE_SET_UP_ERROR = 'DELETE_SET_UP_ERROR'

export const SET_UP_AUTHENTICATION = 'SET_UP_AUTHENTICATION'
export const SET_UP_AUTHENTICATION_SUCCESS = 'SET_UP_AUTHENTICATION_SUCCESS'
export const SET_UP_AUTHENTICATION_ERROR = 'SET_UP_AUTHENTICATION_SUCCESS'

export const FETCH_SET_UP = 'FETCH_SET_UP'
export const FETCH_SET_UP_SUCCESS = 'FETCH_SET_UP_SUCCESS'
export const FETCH_SET_UP_ERROR = 'FETCH_SET_UP_ERROR'

export const VERIFY_AUTHENTICATION = 'VERIFY_AUTHENTICATION'
export const VERIFY_AUTHENTICATION_SUCCESS = 'VERIFY_AUTHENTICATION_SUCCESS'
export const VERIFY_AUTHENTICATION_ERROR = 'VERIFY_AUTHENTICATION_ERROR'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const VERIFY_OTP = 'VERIFY_OTP'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR'

export const SAVE_OTP = 'SAVE_OTP'
