export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR'

export const SET_STUDENT_LIST = 'SET_STUDENT_LIST'
export const SET_STUDENT_LIST_SUCCESS = 'SET_STUDENT_LIST_SUCCESS'
export const SET_STUDENT_LIST_ERROR = 'SET_STUDENT_LIST_ERROR'

export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA'
export const UPDATE_STUDENT_DATA_SUCCESS = 'UPDATE_STUDENT_DATA_SUCCESS'
export const UPDATE_STUDENT_DATA_ERROR = 'UPDATE_STUDENT_DATA_ERROR'

export const FETCH_STUDENT_NATIONALITY = 'FETCH_STUDENT_NATIONALITY'
export const FETCH_STUDENT_NATIONALITY_SUCCESS = 'FETCH_STUDENT_NATIONALITY_SUCCESS'
export const FETCH_STUDENT_NATIONALITY_ERROR = 'FETCH_STUDENT_NATIONALITY_ERROR'

export const UPDATE_STUDENT_NATIONALITY = 'UPDATE_STUDENT_NATIONALITY'
export const UPDATE_STUDENT_NATIONALITY_SUCCESS = 'UPDATE_STUDENT_NATIONALITY_SUCCESS'
export const UPDATE_STUDENT_NATIONALITY_ERROR = 'UPDATE_STUDENT_NATIONALITY_ERROR'

export const FETCH_STUDENT_FAMILY_MEMBERS = 'FETCH_STUDENT_FAMILY_MEMBERS'
export const FETCH_STUDENT_FAMILY_MEMBERS_SUCCESS = 'FETCH_STUDENT_FAMILY_MEMBERS_SUCCESS'
export const FETCH_STUDENT_FAMILY_MEMBERS_ERROR = 'FETCH_STUDENT_FAMILY_MEMBERS_ERROR'

export const UPDATE_STUDENT_FAMILY_MEMBERS = 'UPDATE_STUDENT_FAMILY_MEMBERS'
export const UPDATE_STUDENT_FAMILY_MEMBERS_SUCCESS = 'UPDATE_STUDENT_FAMILY_MEMBERS_SUCCESS'
export const UPDATE_STUDENT_FAMILY_MEMBERS_ERROR = 'UPDATE_STUDENT_FAMILY_MEMBERS_ERROR'

export const SET_FAMILY_MEMBERS = 'SET_FAMILY_MEMBERS'
export const SET_FAMILY_MEMBERS_SUCCESS = 'SET_FAMILY_MEMBERS_SUCCESS'
export const SET_FAMILY_MEMBERS_ERROR = 'SET_FAMILY_MEMBERS_ERROR'

export const DELETE_FAMILY_MEMBERS = 'DELETE_FAMILY_MEMBERS'
export const DELETE_FAMILY_MEMBERS_SUCCESS = 'DELETE_FAMILY_MEMBERS_SUCCESS'
export const DELETE_FAMILY_MEMBERS_ERROR = 'DELETE_FAMILY_MEMBERS_SUCCESS'

export const FETCH_FAMILY_MEMBER_NATIONALITY = 'FETCH_FAMILY_MEMBER_NATIONALITY'
export const FETCH_FAMILY_MEMBER_NATIONALITY_SUCCESS = 'FETCH_FAMILY_MEMBER_NATIONALITY_SUCCESS'
export const FETCH_FAMILY_MEMBER_NATIONALITY_ERROR = 'FETCH_FAMILY_MEMBER_NATIONALITY_ERROR'

export const UPDATE_FAMILY_MEMBER_NATIONALITY = 'UPDATE_FAMILY_MEMBER_NATIONALITY'
export const UPDATE_FAMILY_MEMBER_NATIONALITY_SUCCESS = 'UPDATE_FAMILY_MEMBER_NATIONALITY_SUCCESS'
export const UPDATE_FAMILY_MEMBER_NATIONALITY_ERROR = 'UPDATE_FAMILY_MEMBER_NATIONALITY_ERROR'

export const FETCH_ALL_NATIONALITIES = 'FETCH_ALL_NATIONALITIES'
export const FETCH_ALL_NATIONALITIES_SUCCESS = 'FETCH_ALL_NATIONALITIES_SUCCESS'
export const FETCH_ALL_NATIONALITIES_ERROR = 'FETCH_ALL_NATIONALITIES_ERROR'

export const FETCH_ACTIVE_SECTIONS = 'FETCH_ACTIVE_SECTIONS'
export const ADD_ROW_FAMILY = 'ADD_ROW_FAMILY'

export const SUBMIT_STUDENT_SECTION = 'SUBMIT_STUDENT_SECTION'
export const SELECTED_STUDENT_ROW = 'SELECTED_STUDENT_ROW'

export const SELECTED_ROLE = 'SELECTED_ROLE'

